using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Vrocky.AdbMonkey
{
    public class KeyCodes
    {
        public const int EV_ABS = 3;
        public const int KEY_BACK = 158;
        public const int EV_REP = 20;
        public const int KEY_COMMA = 51;
        public const int SYN_MT_REPORT = 2;
        public const int KEY_DOWN = 108;
        public const int KEY_ESC = 1;
        public const int KEY_INSERT = 110;
        public const int KEY_RIGHT = 106;
        public const int KEY_APOSTROPHE = 40;
        public const int SYN_REPORT = 0;
        public const int KEY_BACKSLASH = 43;
        public const int EV_LED = 17;
        public const int KEY_F4 = 62;
        public const int KEY_F3 = 61;
        public const int KEY_GRAVE = 41;
        public const int ABS_MT_PRESSURE = 58;
        public const int KEY_SHOP = 221;
        public const int KEY_C = 46;
        public const int KEY_SPACE = 57;
        public const int KEY_LEFTBRACE = 26;
        public const int KEY_F10 = 68;
        public const int EV_KEY = 1;
        public const int ABS_MT_POSITION_X = 53;
        public const int ABS_MT_POSITION_Y = 54;
        public const int KEY_KBDILLUMDOWN = 229;
        public const int KEY_END = 107;
        public const int KEY_VOLUMEDOWN = 114;
        public const int KEY_RIGHTBRACE = 27;
        public const int EV_REL = 2;
        public const int KEY_POWER = 116;
        public const int KEY_DOT = 52;
        public const int KEY_9 = 10;
        public const int KEY_8 = 9;
        public const int KEY_F5 = 63;
        public const int KEY_VOLUMEUP = 115;
        public const int KEY_5 = 6;
        public const int KEY_4 = 5;
        public const int KEY_7 = 8;
        public const int KEY_6 = 7;
        public const int KEY_1 = 2;
        public const int KEY_0 = 11;
        public const int KEY_3 = 4;
        public const int KEY_2 = 3;
        public const int KEY_CAPSLOCK = 58;
        public const int KEY_RIGHTALT = 100;
        public const int KEY_F2 = 60;
        public const int KEY_F1 = 59;
        public const int KEY_F12 = 88;
        public const int KEY_Y = 21;
        public const int KEY_X = 45;
        public const int KEY_Z = 44;
        public const int KEY_U = 22;
        public const int KEY_T = 20;
        public const int KEY_W = 17;
        public const int KEY_V = 47;
        public const int KEY_Q = 16;
        public const int KEY_P = 25;
        public const int KEY_S = 31;
        public const int KEY_R = 19;
        public const int KEY_M = 50;
        public const int KEY_L = 38;
        public const int KEY_O = 24;
        public const int KEY_N = 49;
        public const int KEY_I = 23;
        public const int KEY_H = 35;
        public const int KEY_K = 37;
        public const int KEY_J = 36;
        public const int KEY_E = 18;
        public const int KEY_D = 32;
        public const int KEY_G = 34;
        public const int KEY_F = 33;
        public const int KEY_A = 30;
        public const int KEY_TAB = 15;
        public const int EV_SYN = 0;
        public const int KEY_BACKSPACE = 14;
        public const int KEY_UP = 103;
        public const int KEY_DELETE = 111;
        public const int KEY_PAGEUP = 104;
        public const int KEY_B = 48;
        public const int KEY_LEFT = 105;
        public const int KEY_HOME = 102;
        public const int KEY_SLASH = 53;
        public const int KEY_PAGEDOWN = 109;
        public const int KEY_F11 = 87;
        public const int BTN_TOUCH = 330;
        public const int KEY_LEFTSHIFT = 42;
        public const int KEY_F6 = 64;
        public const int KEY_MINUS = 12;
        public const int KEY_EQUAL = 13;
        public const int REL_WHEEL = 8;
        public const int KEY_ENTER = 28;
        public const int KEY_F7 = 65;
        public const int KEY_F9 = 67;
        public const int KEY_LEFTMETA = 125;
        public const int KEY_SEMICOLON = 39;
        public const int DOWN = 1;
        public const int UP = 0;
    }
}
